### ISSUE TITLE
Service Module landing page

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#11]
AS an Administrative User
I WANT TO have a separate sub-module of admin portal
SO THAT I CAN start creating a new service and/or view and edit existing services

### Acceptance Criteria

- [x] button  "Loo uus teenus" ("Create new service") created (directs to Training Module Intents view)
- [ ] "message board" for system notes created (messages to be printed out to Bürokratt user like "New services have been created, **train model**" _-- the latter refers to an appropriate Training Module's link_)
- [x] table containing "Olemasolevad teenused" (Existing services) created
- [ ] table columns: Teenuse nimi (Service name); Teenuse kasutamise arv (Times Service has been triggered); Muuda teenust (Edit Service), takes to #12 ; Teenuse olek (Activate/Deactivate Service) [action]; Kustuta teenus (Delete Service) [action] created, takes to #14 
- [x] conformation pop-up with information about deletion process (i.e. data will be deleted etc) created and triggered when Delete service button is pressed
- [x] when changing the status of a Service, a modal to confirm or discard the selection (with appropriate information) appears

#### GUI

- [x] All input as configurable `i18n` values

#### DSL

- [x] #38
- [x] #39
- [ ] Delete an inactive Service by using #14 and following #24
- [ ] #41

**Comment by SigritSiht** [comment]
![Image](https://user-images.githubusercontent.com/25658198/192512026-4bd83905-7642-4cef-83c1-0e1f8b9f7574.png)

**Comment by SigritSiht** [comment]
@Minwasko discussed with UX. 4.AC should be changed to Muuda - > directs to intent in Training Module.

**Comment by 1AhmedYasser** [comment]
@allarlaaneleht @turnerrainer  i contacted the developer who worked on it and he mentioned the following 
```
We never got the final decision on what it should actually do. It was supposed to point somewhere inside training module, as theoretically 1st step for creating a service starts there, but we didn’t fully connect them, so never got the final answer on what to do with it and we agreed that it would stay as is for now
```
What is your plan with it at the moment

**Comment by allarlaaneleht** [comment]
BUG: The link "Treeni uus mudel" directs to localhost URL.
![treeniuusmudellink](https://github.com/buerokratt/Service-Module/assets/139747282/6f8d3edd-14bd-4506-a60f-3219f95c1332)

![image](https://github.com/buerokratt/Service-Module/assets/139747282/f354a2fc-5145-4d49-8426-ded6f03f31fc)

**Comment by allarlaaneleht** [comment]
> @allarlaaneleht @turnerrainer i contacted the developer who worked on it and he mentioned the following
> 
> `We never got the final decision on what it should actually do. It was supposed to point somewhere inside training module, as theoretically 1st step for creating a service starts there, but we didn’t fully connect them, so never got the final answer on what to do with it and we agreed that it would stay as is for now`
> 
> What is your plan with it at the moment

@1AhmedYasser Change button should direct you to the service module connection page in order to change an already existing service.

**Comment by turnerrainer** [comment]
https://github.com/buerokratt/Service-Module/issues/142 should be used to create this new funcitonality. Not a bug.

**Comment by 1AhmedYasser** [comment]
> 3\. http://localhost:3001/treening/treeni-uus-mudel

@varmoh
This link should be configured on the environment to point to training module in docker compose here 

```
gui_dev:
    container_name: gui_dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8085
      - REACT_APP_TRAINING_MODULE_GUI_BASE_URL=http://localhost:3001
      - PORT=3006
    build:
      context: ./GUI
      dockerfile: Dockerfile.dev
    ports:
      - 3006:3006
    volumes:
      - /app/node_modules
      - ./GUI:/app
    networks:
      - bykstack
```
