### ISSUE TITLE
[BUG] Intent response is not shown in Training module after connecting to a service.

### ISSUE THREAD

**Issue by IgorKrupenja** [buerokratt/Service-Module#424]
**Steps**

1. Open Services -> Overview in the menu.
2. Click on Ready button for any service in Ready state.
3. Click Connect to intent.
4. Click Connect next to any service.
5. Go to Training -> Training -> Intents.
6. Open the intent you just connected.

Response field is empty.

**Expected behaviour**

The service endpoint should be shown in the Response field.

**Technical notes**

`domain-intent-service-link.yml` does not update OpenSearch after changes in the domain file.

Need to:

1. Add pipelines image to the Service module. For now, copy over from the Training module.
2. Update `domain-intent-service-link.yml` with something like this:

```yaml
updateOpenSearch:
  call: http.post
  args:
    url: "[#TRAINING_PIPELINE]/bulk/domain"
    body:
      input: ${domainYaml.response.body.json}
  result: updateSearchResult
  next: returnSuccess
```
