### ISSUE TITLE
[BUG] Error at end-conversation step

### ISSUE THREAD

**Issue by matKlju** [buerokratt/Service-Module#496]
**Bug description:**
When triggering "EURO-valuuta" service in the test environment, [test](https://test.buerokratt.ee/)
the chatbot crashes, the system throws an error:
![Image](https://github.com/user-attachments/assets/2deedd0e-15ff-4c54-beab-9369c7d1b75c)

It can be seen in the logs that the service fails on step 'finishing-step-end-16'
```
finishing-step-end-16:
  template: "[#SERVICE_PROJECT_LAYER]/end-conversation"
  requestType: templates
  body:
    message: Teenus on lõpetatud
  result: finishing-step-end-16_result
  next: formatMessages
```
```
SERVICE_PROJECT_LAYER=http://component-byk-ruuter-private:8080/services
```

Error log:
[full_log.txt](https://github.com/user-attachments/files/20053756/full_log.txt)

"EURO-valuuta" service yaml:
[EURO-valuuta.txt](https://github.com/user-attachments/files/20053784/EURO-valuuta.txt)

**Expected behavior:**
The request against end-conversation yaml should pass and the general service flow should return a service response..

**Screenshots:**
![Image](https://github.com/user-attachments/assets/169fec61-877a-47a6-9786-34a331c6ea43)
![Image](https://github.com/user-attachments/assets/6da95013-4d1b-4b6f-bb2e-5cdcbaa66906)
